# Generated by Django 5.0.7 on 2026-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_pendingattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='radius_meters',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Radius in meters for geofencing validation', max_digits=10),
        ),
    ]
